[tool.poetry]
name = "codegen"
version = "0.1.0"
description = ""
authors = ["Kate Yanchenko <kate.yanchenka@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
